### PR TITLE
Log stderr messages at info and not error level.

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by puiterwijk** [comment]
I would disagree with this: if something is reported via stderr, it tends to be an error.

**Comment by bowlofeggs** [comment]
@puiterwijk I don't believe that's true - stderr is very often used for "debug" statements. If anything, it's used pretty inconsistently by lots of software, but I'd definitely claim that it isn't "usually" an error when written to stderr, despite the name.

One thing we could do is to use ```log.error()``` when the exit code isn't 0, and use log.info() if it is 0…

**Comment by puiterwijk** [comment]
Then maybe add a flag stderr_is_info to the call() function to indicate whether or not that's the case for the current tool?

**Comment by bowlofeggs** [comment]
@puiterwijk I don't think anyone has the time or patience to study each tool to determine how it uses stderr. IMO logging debug/info statements as ERROR is misleading/timewasting. If the exit code was 0, it's very unlikely that it's an error message, or at least that it's an error message that needs attention.

**Comment by puiterwijk** [comment]
I still disagree, since if stuff sends debuginfo to stderr that's a bug in that binary.
However, I will acknowledge you are now the primary maintainer of this, and the code itself looks good even if I disagree, so +1.

**Review by puiterwijk — APPROVED** [review]

**Comment by dustymabe** [comment]
how about we send stderr to the `warn` level and then send a message to `error` if the exit code was bad. 

so `error` on bad exit code, but then the stderr messages are in `warn` level so someone can easily find them because they should be right before the `error` message about the bad exit code.

**Comment by bowlofeggs** [comment]
@dustymabe The problem is that lots of programs send things that aren't warnings to stderr. In fact, I'd posit that *most* information sent to stderr is not warnings or errors, but just detail info.

**Comment by dustymabe** [comment]
another option is to "prepend" the output with "STDERR:" on the info stream so it's clear where the output came from.

**Comment by bowlofeggs** [comment]
I think I'm just going to go with the option of checking the exit code and using that to determine which log level to use. It's simple, and it will avoid raising eyebrows when they don't need to be raised.

**Pull request merged**
